### ISSUE TITLE
Can clipboardjs be made into an npm lib? (minus the ie check)

### ISSUE THREAD

**Issue by QuantumInformation** [Code-Inside/Samples#2]
If not I was thinking of making one as I use it a lot.

**Comment by QuantumInformation** [comment]
basically I would just have:

![image](https://cloud.githubusercontent.com/assets/216566/24154402/fb8c383c-0e48-11e7-9ded-e3fcb4ae394e.png)

**Comment by robertmuehsig** [comment]
Sure - but the API is super strange. I found a case where the clipboard didn't get updated even when the console.log claimed that everything worked. 
I tried to use the logic inside a jQuery/bootstrap dialog and somehow Chrome didn't accepted the content in the clipboard. I guess it could have something to do with z-indexes.

Besides this: Go ahead - I'm not that familiar with npm or how to create a package.

**Comment by QuantumInformation** [comment]
Thanks Robert, are you the original author so I can give credit?

**Comment by robertmuehsig** [comment]
Nope, I found it here http://stackoverflow.com/a/30810322/602449 (and maybe some other SO threads). Have fun :)

**Comment by QuantumInformation** [comment]
So far the code is worked for me, I'll let you know if I can reproduce your issue.

**Comment by robertmuehsig** [comment]
Ay - and if you are done with your npm package, please inform me. I would like to add that npm link to the blogpost :)
